parameters:
    hgabka_kunstmaan_email.mail_builder.class: 'Hgabka\KunstmaanEmailBundle\Helper\MailBuilder'
    hgabka_kunstmaan_email.message_logger.class: 'Hgabka\KunstmaanEmailBundle\Logger\MessageLogger'
    hgabka_kunstmaan_email.message_sender.class: 'Hgabka\KunstmaanEmailBundle\Helper\MessageSender'

services:
    hgabka_kunstmaan_email.mail_builder:
        class: '%hgabka_kunstmaan_email.mail_builder.class%'
        arguments: ["@doctrine", "@mailer", "@request_stack", "@hgabka_kunstmaan_email.queue_manager", "@hgabka_kunstmaan_email.param_substituter", "@translator", "@hgabka_kunstmaan_email.message_logger"]

    hgabka_kunstmaan_email.message_sender:
        class: '%hgabka_kunstmaan_email.message_sender.class%'
        arguments: ["@doctrine", "@mailer", "@request_stack", "@hgabka_kunstmaan_email.queue_manager", "@hgabka_kunstmaan_email.param_substituter", "@translator", "@hgabka_kunstmaan_email.message_logger"]

    hgabka_kunstmaan_email.message_logger:
        class: '%hgabka_kunstmaan_email.message_logger.class%'
        arguments: ["@logger", '']

    hgabka_kunstmaan_email.email_logger:
        class: 'Hgabka\KunstmaanEmailBundle\Logger\EmailLogger'
        arguments: ["@doctrine"]

    hgabka_kunstmaan_email.queue_manager:
        class: 'Hgabka\KunstmaanEmailBundle\Helper\QueueManager'
        arguments: ["@doctrine", "@mailer", '', '']

    hgabka_kunstmaan_email.param_substituter:
        class: 'Hgabka\KunstmaanEmailBundle\Helper\ParamSubstituter'
        arguments: ["@request_stack", "%kernel.cache_dir%", '']

    hgabka_kunstmaan_email.email_subscriber:
        class: Hgabka\KunstmaanEmailBundle\EventListener\EmailSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    hgabka_kunstmaan_email.mailer_subscriber:
        class: Hgabka\KunstmaanEmailBundle\EventListener\MailerSubscriber
        arguments: ["@hgabka_kunstmaan_email.email_logger", '']
        tags:
            - { name: kernel.event_subscriber }

    hgabka_kunstmaan_email.mail_logger_plugin:
        class: Hgabka\KunstmaanEmailBundle\Mailer\MessageLoggerPlugin
        arguments: ['']
        tags:
            - { name: "swiftmailer.default.plugin" }

